namespace NodeJS {
	interface ProcessEnv {
		NEXT_PUBLIC_CLIENT_BASE_URL: string
		NEXT_PUBLIC_API_BASE_URL_QUERY_SERVER: string
		NEXT_PUBLIC_API_BASE_URL_QUERY_CLIENT: string
		NEXT_PUBLIC_API_BASE_URL_AUTH_SERVER: string
		NEXT_PUBLIC_API_BASE_URL_AUTH_CLIENT: string
		NEXT_PUBLIC_API_BASE_URL_COMMAND: string
		NEXT_PUBLIC_API_BASE_URL_IMAGE_CLIENT: string
		NEXT_PUBLIC_API_BASE_URL_IMAGE_SERVER: string
	}
}
