@host=http://localhost:3001/profile
@JWT=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImF1dGgtYmFzZS1rZXkifQ.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6MSwiZW1haWwiOiJzZWFtdXMuaG9lZ2VyMzdAZXRoZXJlYWwuZW1haWwiLCJzdGF0dXMiOiJ1bnZlcmlmaWVkIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NzQ0NzQxNDgsImV4cCI6MTY3NDQ3NTA0OH0.i7KiN9hTQIhCcJzaTcTOKpH2YzVaGYwJolTL8yxzBx1dcF-R984a-npEW1YL_Las8c_Sr94rnUouGkhuWhRnP8XgMzitfzNkm7ColW2jCdETdYNbwxuDcll57PDbTL3_OnC1eVWwEG2xg52E7F0J5zaeB8GCDqKIBl0wn0j3v34

### Get profile related to access token (includes email & last login)
GET {{host}}/me
Authorization: Bearer {{JWT}} 

### Get profile by userId (does not include email & last login)
GET {{host}}/1
Authorization: Bearer {{JWT}} 


