@host=http://localhost:3001/profile
@JWT=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImF1dGgtYmFzZS1rZXkifQ.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6MSwiZW1haWwiOiJzZWFtdXMuaG9lZ2VyMzdAZXRoZXJlYWwuZW1haWwiLCJzdGF0dXMiOiJ1bnZlcmlmaWVkIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NzQ0MDY0MjYsImV4cCI6MTY3NDQwNzMyNn0.WiGxXrT0AGAz7Yd1PboXfV9_2ZAqXT69kSjaM8IHAodQagve4n9H-uKhWrCll7VwC6Iq1FDj3AKMxRlxyxLh0Gqv2tRM9O58zaE5IakbsJ1_SNkk35d8qAe0CMLAcHvg5iUsZkT0fb2NHrzuq2HrnXJYWowqlPGXZ8kP5EGMmtU

###
GET {{host}}/me
Authorization: Bearer {{JWT}} 

###
GET {{host}}/1
Authorization: Bearer {{JWT}} 


