@host=http://localhost:3005/auth

POST {{host}}/signup
Content-Type: application/json

{
    "username": "test",
    "email": "test@test.de",
    "password": "alsoSomethingWithtest"
}

###

POST {{host}}/login
Content-Type: application/json

{
  "email": "test@test.de",
  "password": "alsoSomethingWithtest" 
}
