@host=http://localhost:3005/auth
@resetToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QHRlc3QuZGUiLCJpYXQiOjE2NzEyODc2MDQsImV4cCI6MTY3MTMyMzYwNH0.JLdYxMXLyLuL18Emo4MnPHfPOZXvAgylvPLxG9n124bJhPpq9AF1hjTjwKIT1sutkooU8Op5P9E0yzPrnHx-kxX2ZEsjtNPlQ_nQZyPHQD4R-Quoj1e2CFOTuO9HRen_AlgpBVR22rU8yPhJqgLeHqk6lhW-xgfGTPjV91FbeYE
POST {{host}}/signup
Content-Type: application/json

{
    "username": "test",
    "email": "seamus.hoeger37@ethereal.email",
    "password": "alsoSomethingWithtest"
}

###

POST {{host}}/login
Content-Type: application/json

{
  "email": "seamus.hoeger37@ethereal.email",
  "password": "alsoSomethingWithtest" 
}

###
POST {{host}}/refresh
Authorization: Bearer {{resetToken}} 