@host=http://localhost:3005/profile
@JWT=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImF1dGgtYmFzZS1rZXkifQ.eyJpZCI6MSwiZW1haWwiOiJzZWFtdXMuaG9lZ2VyMzdAZXRoZXJlYWwuZW1haWwiLCJpYXQiOjE2NzMxOTY4MDQsImV4cCI6MTY3MzIzMjgwNH0.NwWkVOeUTV9k72hHF_qQ_1WtGfG9lz0-vZ1gXdfty2PKxyH6dkSx7lt9yX30LtMzQkMktrWUuqMBUDgrixmiH8XMIOPXeJkgpW_S8XqD5_yn_KMKgEjXKUxmfW_r6GcP9-3m3sERzKtqiiJ4T5AXnsoO_GAhwTg9dSsUHpZYK-0

###
GET {{host}}/me
Authorization: Bearer {{JWT}} 

###
GET {{host}}/1
Authorization: Bearer {{JWT}} 


