@host=http://localhost:3005/account
@jwt=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6MSwiZW1haWwiOiJzZWFtdXMuaG9lZ2VyMzdAZXRoZXJlYWwuZW1haWwiLCJzdGF0dXMiOiJ1c2VyIiwicm9sZSI6InVudmVyaWZpZWQiLCJpYXQiOjE2NzEyOTIzMjksImV4cCI6MTY3MTI5MzIyOX0.ADq5MGV_cdXp5NEYKqFcVYQwDXORiKn2ESZDuDYkdftK962thLPEEWJHBhjf-RYqyuXpbytcEEuP0xEqUEtak2qXjuH4mKnpZ93zUnGqrXvh1ovTPBCPcD1NAZKa-QQ_7CbKv98Oss_A8Ep3UC64iaUnJ-MjsL2TknzvhdmoPyo
@resetJWT=
@mailJWT=


###
GET {{host}}/resend-verification-email
Authorization: Bearer {{jwt}}

###
POST {{host}}/send-password-reset-mail
Content-Type: application/json

{
    "email": "test@test.test"
}

###
POST {{host}}/reset-password
Content-Type: application/json
Authorization: Bearer {{resetJWT}}

{
    "password": "newPassword"
}

###
GET {{host}}/verify-email
Authorization: Bearer {{mailJWT}}

